name: Build and Push FastAPI Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Check out code on main branch
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub using Github Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Obtain Git SHA checksum of the commit, truncated to a short version 
    - name: Extract Git SHA
      id: vars
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # Build image on Docker
    - name: Build image
      run: |
        docker build -t megafood/fastapi-hello:${{ steps.vars.outputs.sha }} .

    # Push image to Docker
    - name: Push image
      run: |
        docker push megafood/fastapi-hello:${{ steps.vars.outputs.sha }}

    # Notify the webhook server to proceed to run ansible playbooks
    - name: Notify webhook
      run: |
        curl -X POST https://damon-unreiterating-unspatially.ngrok-free.dev/webhook \
        -H 'Content-Type: application/json' \
        -d "{\"sha\": \"${{ steps.vars.outputs.sha }}\"}"
