name: Build and Push FastAPI Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Git SHA
      id: vars
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build image
      run: |
        docker build -t megafood/fastapi-hello:${{ steps.vars.outputs.sha }} .

    - name: Push image
      run: |
        docker push megafood/fastapi-hello:${{ steps.vars.outputs.sha }}

    - name: Notify webhook
      run: |
        curl -X POST https://damon-unreiterating-unspatially.ngrok-free.dev:9000/webhook \
        -H 'Content-Type: application/json' \
        -d "{\"sha\": \"${{ steps.vars.outputs.sha }}\"}"
